import type { GalleryCategory, GalleryPhoto } from "@/types/gallery";

export const galleryCategories: GalleryCategory[] = [
  {
    title: "Dzikie zwierzeta",
    slug: "wildlife",
    description: "Spotkania z duzymi ssakami i tropami ukrytymi w gestwinie.",
  },
  {
    title: "Ptaki",
    slug: "birds",
    description: "Lot, cierpliwosc i chwila, w ktorej cisza zaczyna drzec.",
  },
  {
    title: "Las",
    slug: "forest",
    description: "Mrok pni, wilgotny mech i swiatlo przechodzace przez korony.",
  },
  {
    title: "Poranki w naturze",
    slug: "mornings",
    description: "Mgla, rosa i pierwsze minuty dnia zapisane w kadrze.",
  },
];

export const galleryPhotos: GalleryPhoto[] = [
  {
    id: "stag-dawn",
    slug: "jelen-o-swicie",
    title: "Jelen o swicie",
    category: "wildlife",
    location: "Bory Dolnoslaskie",
    date: "Pazdziernik 2025",
    aspectRatio: "landscape",
    width: 1920,
    height: 1280,
    imageSrc: "/images/hero3.jpg",
    alt: "Jelen stojacy w mrocznym lesie o swicie",
  },
  {
    id: "bison-fog",
    slug: "zubr-w-porannej-mgle",
    title: "Zubr w porannej mgle",
    category: "wildlife",
    location: "Puszcza Bialowieska",
    date: "Listopad 2025",
    aspectRatio: "tall",
    alt: "Placeholder zdjecia zubra w lesie",
  },
  {
    id: "owl-flight",
    slug: "sowa-nisko-nad-trawa",
    title: "Sowa nisko nad trawa",
    category: "birds",
    location: "Dolina Biebrzy",
    date: "Wrzesien 2025",
    aspectRatio: "landscape",
    alt: "Placeholder zdjecia sowy w locie",
  },
  {
    id: "kingfisher",
    slug: "zimorodek-nad-brzegiem",
    title: "Zimorodek nad brzegiem",
    category: "birds",
    location: "Mazowsze",
    date: "Czerwiec 2025",
    aspectRatio: "square",
    alt: "Placeholder zdjecia zimorodka",
  },
  {
    id: "wolf-line",
    slug: "wilk-na-linii-drzew",
    title: "Wilk na linii drzew",
    category: "wildlife",
    location: "Roztocze",
    date: "Styczen 2026",
    aspectRatio: "portrait",
    alt: "Placeholder zdjecia wilka w lesie",
  },
  {
    id: "old-forest",
    slug: "stary-las-po-deszczu",
    title: "Stary las po deszczu",
    category: "forest",
    location: "Beskid Niski",
    date: "Maj 2025",
    aspectRatio: "tall",
    alt: "Placeholder zdjecia starego lasu",
  },
  {
    id: "pine-light",
    slug: "swiatlo-miedzy-sosnami",
    title: "Swiatlo miedzy sosnami",
    category: "forest",
    location: "Kampinos",
    date: "Kwiecien 2025",
    aspectRatio: "landscape",
    alt: "Placeholder zdjecia lasu z promieniami swiatla",
  },
  {
    id: "mist-field",
    slug: "mgla-nad-laka",
    title: "Mgla nad laka",
    category: "mornings",
    location: "Podlasie",
    date: "Sierpien 2025",
    aspectRatio: "landscape",
    alt: "Placeholder zdjecia porannej mgly",
  },
  {
    id: "fox-gold",
    slug: "lis-w-zlotym-swietle",
    title: "Lis w zlotym swietle",
    category: "wildlife",
    location: "Lubelszczyzna",
    date: "Lipiec 2025",
    aspectRatio: "square",
    alt: "Placeholder zdjecia lisa",
  },
  {
    id: "cranes",
    slug: "zurawie-przed-odlotem",
    title: "Zurawie przed odlotem",
    category: "birds",
    location: "Warta",
    date: "Marzec 2025",
    aspectRatio: "portrait",
    alt: "Placeholder zdjecia zurawi",
  },
  {
    id: "dew-morning",
    slug: "rosa-na-trawach",
    title: "Rosa na trawach",
    category: "mornings",
    location: "Biebrza",
    date: "Maj 2025",
    aspectRatio: "tall",
    alt: "Placeholder zdjecia rosy o poranku",
  },
  {
    id: "forest-path",
    slug: "sciezka-w-glab-boru",
    title: "Sciezka w glab boru",
    category: "forest",
    location: "Puszcza Knyszynska",
    date: "Pazdziernik 2025",
    aspectRatio: "portrait",
    alt: "Placeholder zdjecia lesnej sciezki",
  },
];
